Unit tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -94,7 +94,22 @@ jobs:
             export CRYPTO_QUEUE_URL=${CRYPTO_QUEUE_URL}
 
             cd DESA_API_2/ || exit 1
+
+            # Verifica la existencia de Dockerfile y task-def.json
+            if [ ! -f "backend/Dockerfile" ]; then
+              echo "ERROR: Dockerfile no encontrado en el directorio backend."
+              exit 1
+            fi
+
+            if [ ! -f "backend/task-def.json" ]; then
+              echo "ERROR: Archivo task-def.json no encontrado en el directorio backend."
+              exit 1
+            fi
+
+            git fetch origin
+            git checkout \${{ github.event.pull_request.head.ref }}
             git pull origin \${{ github.event.pull_request.head.ref }}
+
             cd backend
 
             # Log in to Amazon ECR
